### ISSUE TITLE
v0.12.0

### ISSUE THREAD

**Issue by lukasschlueter** [pfernie/cookie_store#13]
https://crates.io/crates/cookie_store/versions lists v0.12.0 as the latest version, however the code in this [repo is still on v0.11.0](https://github.com/pfernie/cookie_store/blob/ab29f1c939efc6c0642bed00fedb13c9dec72e29/Cargo.toml#L5). Are there more differences than just the version number?

Additionally, the "percent-encode" feature of the `cookie` crate seems to be unused (I was working on a PR to remove it when I realized the version difference), so I guess it can be removed in a v0.12.1 :-)

**Comment by pfernie** [comment]
Thanks for reporting this; seems I never pushed up the `v0.12.0` tag! The only missing change was indeed the `Cargo.toml` version, but it is updated now.

Feel free to open a new PR or Issue regarding `percent-encode`, but off the cuff having this feature enabled changes encode/decode behavior within `cookie-rs`, so I am unclear on your meaning/intent.
