### ISSUE TITLE
`CookieStore::from_cookies` is private

### ISSUE THREAD

**Issue by qm3ster** [pfernie/cookie_store#19]
Is there a motivating reason why `CokieStore::from_cookies` should not be publically available?
My use case is loading cookies from a stream that isn't newline-delimited.

I also noticed that since both `load` and `from_cookies` check for expiration, the checks happens twice for `load` and `load_json` endpoints:
`Deserialize for CookieStore` -> `CookieStoreVisitor` -> `from_cookies` ✔️ 
`load` (checks) -> `from_cookies` (checks again) ❌
`load_json` -> `load` (checks) -> `from_cookies` (checks again) ❌

Personally, I would move it out of `from_cookies` and into `CookieStoreVisitor`, because I believe there should be a way to load expired cookies, at least at the lowest level.

**Comment by pfernie** [comment]
There is no specific reason `from_cookies` is private; I have opened #23 making it `pub`. For the other comments, I agree there should be an escape hatch; the PR therefore also introduces `load_all` and `load_json_all`. This preserves the existing behavior in the prior API, but allows for the behavior suggested, while also removing the redundant check.

It does not introduce analogous `save_all`/`save_json_all` methods, as that feels further from the intent/spirit of the RFC.

**Comment by pfernie** [comment]
#23 has been merged and published as part of release v0.16.1
