### ISSUE TITLE
0.15.2 is breaking

### ISSUE THREAD

**Issue by Ten0** [pfernie/cookie_store#21]
`0.15.2` contains breaking changes, because it updates dependencies that are part of its public interface (specifically [`RawCookie`](https://docs.rs/cookie_store/latest/cookie_store/struct.CookieStore.html#method.insert_raw)).
This broke [`reqwest`](https://crates.io/crates/reqwest) (https://github.com/seanmonstar/reqwest/issues/1507#issue-1175733273).

It should be yanked, and released as a semver-incompatible update (`0.16`).

**Comment by pfernie** [comment]
Apologies for the breakage; `0.15.2` has been yanked, and `0.16.0` published.
