### ISSUE TITLE
`Cookie` has nearly no API

### ISSUE THREAD

**Issue by jedenastka** [pfernie/cookie_store#22]
`Cookie` exposed by this library has nearly no public API. This makes `CookieStore::save()`, `CookieStore::get()` and other functions that return or pass `Cookie` in some form very limited.

It wraps around a `cookie::Cookie` with loads of useful functions, but it's nearly empty. Example:

```rs
Cookie {
    raw_cookie: Cookie {
        cookie_string: None,
        name: Concrete("foo"),
        value: Concrete("bar"),
        expires: None,
        max_age: None,
        domain: None,
        path: None,
        secure: Some(true),
        http_only: None,
        same_site: Some(Lax),
    },
    path: CookiePath("/", true),
    domain: HostOnly("example.com"),
    expires: AtUtc(
        OffsetDateTime {
            utc_datetime: PrimitiveDateTime {
                date: Date {
                    year: 2022,
                    ordinal: 122,
                },
                time: Time {
                    hour: 20,
                    minute: 12,
                    second: 2,
                    nanosecond: 490509358,
                },
            },
            offset: UtcOffset {
                hours: 0,
                minutes: 0,
                seconds: 0,
            },
        },
    ),
}
```

The only things you can get from the wrapped `cookie::Cookie` are the `name()`, `value()`, `same_site()` and `secure()`.

You can't get nearly anything from `Cookie` itself either: https://docs.rs/cookie_store/0.16.0/cookie_store/struct.Cookie.html

Example with `reqwest_cookie_store` (`example.com` and `foo=bar` are just examples):
```rs
use std::sync::Arc;

fn main() {
    let cookies = Arc::new(reqwest_cookie_store::CookieStoreMutex::default());

    let client = reqwest::blocking::Client::builder()
        .cookie_store(true)
        .cookie_provider(cookies.clone())
        .build().unwrap();

    client
        .get("https://example.com")
        .send().unwrap();

    {
        let cookies = cookies.lock().unwrap();
        let cookie = cookies
            .get("example.com", "/", "foo").unwrap();

        assert!(cookie.name() == "foo");
        assert!(cookie.value() == "bar");
        assert!(cookie.path() == None);
        assert!(cookie.expires_datetime() == None);
        assert!(cookie.domain() == None);
        assert!(cookie.path() == None);
    };
}
```

**Comment by pfernie** [comment]
The `CookieStore::Cookie` type is intended to be an enriched wrapper around `cookie::Cookie` that adheres to the spec of the RFC. Is your issue here looking to get access to the values that are defaulted in the enriched wrapper? That is, `CookieStore::Cookie::path` field, which in your example is `CookiePath("/", true)` per the rules of the RFC, although the raw `cookie::Cookie::path()` value is `None` (which would be the case if no `Path` directive was included with the cookie). And similarly for `domain`?

**Comment by jedenastka** [comment]
> Is your issue here looking to get access to the values that are defaulted in the enriched wrapper?
Yes.
> And similarly for domain?
Yes.

#24 fixes this.
