### ISSUE TITLE
Upgrade cookie dependency to 0.17

### ISSUE THREAD

**Issue by clitic** [pfernie/cookie_store#35]
I want to use [Cookie::split_parse](https://docs.rs/cookie/latest/cookie/struct.Cookie.html#method.split_parse). If I use cookie crate version `0.17` then I am unable to store this cookie in cookie_store because different cookie crate versions are used which  are `0.16.1` and `0.17`.

https://github.com/pfernie/cookie_store/blob/1a39a9373cedb86ae5325882a371cc0543f65dff/src/cookie.rs#L6

This happens because cookie_store holds a reference to `cookie::Cookie`. I also think cookie crate should be re-exported to avoid such situations.

**Comment by pfernie** [comment]
Implemented via #36 and release `0.20.0`
